export const QUERY_KEY = {
  cities: "cities",
  clublessCities: "clubless-cities",
  countries: "countries",
  clubs: "clubs",
  clubCV: "club-cv",
  countryCV: "country-cv",
  coefficient: "coefficient",
  coefficientGraph: "coefficient-graph",
  tournaments: "tournament",
  tournamentStages: "tournament-stages",
  participants: "participants",
  matches: "matches",
  winners: "winners",
  combat: "combat",
};
